# Generated by Django 5.1.4 on 2025-06-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('featured', 'Featured'), ('on_sale', 'On Sale'), ('top_rated', 'Top Rated'), ('normal', 'Normal')], default='normal', help_text='Product type: Featured, On Sale, Top Rated, or Normal', max_length=20),
        ),
    ]
