# Generated by Django 5.1.4 on 2025-06-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('featured', 'Featured'), ('on_sale', 'On Sale'), ('top_rated', 'Top Rated'), ('normal', 'Normal'), ('clearance', 'Clearance'), ('new_arrivals', 'New Arrivals'), ('limited_quantities', 'Limited Quantities'), ('best_choices', 'The Best Choices')], default='normal', help_text='Product label for homepage filtering', max_length=30),
        ),
    ]
