# Generated by Django 5.1.4 on 2025-06-22 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('featured', 'Featured'), ('on_sale', 'On Sale'), ('top_rated', 'Top Rated'), ('normal', 'Normal'), ('clearance', 'Clearance'), ('new_arrival', 'New Arrivals'), ('limited', 'Limited Quantities'), ('best_choice', 'The Best Choices')], default='normal', help_text='Product label for homepage filtering', max_length=30),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='store.registration')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
