# Generated by Django 5.1.4 on 2025-06-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_added_at_cart_created_at_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created_at',
            new_name='added_at',
        ),
    ]
