# Generated by Django 5.1.4 on 2025-06-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_created_at_cart_added_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
